import { Injectable, Logger } from '@nestjs/common';

import type { AccessContext } from '../../common/auth/auth.types.js';
import { Errors } from '../../common/errors/api-exception.js';
import type { Report } from '../../generated/prisma/client.js';
import { ReportStatus } from '../../generated/prisma/enums.js';
import { PrismaService } from '../../infrastructure/prisma/prisma.service.js';
import { QueueService } from '../../infrastructure/queue/queue.service.js';
import { StorageService } from '../../infrastructure/storage/storage.service.js';

import type { CreateReportDto, ReportDto } from './dto/analytics.dto.js';

const LIST_LIMIT = 50;

/** Report requests: persisted immediately, generated by the reports worker. */
@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly queue: QueueService,
    private readonly storage: StorageService,
  ) {}

  async create(access: AccessContext, input: CreateReportDto): Promise<ReportDto> {
    if (input.projectId) {
      const exists = await this.prisma.project.count({
        where: { id: input.projectId, organizationId: access.organizationId, deletedAt: null },
      });
      if (!exists) throw Errors.field('projectId', 'Project not found');
    }
    const report = await this.prisma.report.create({
      data: {
        organizationId: access.organizationId,
        requestedById: access.userId,
        type: input.type,
        params: input.projectId ? { projectId: input.projectId } : {},
      },
    });
    try {
      await this.queue.generateReport(report.id);
    } catch (error) {
      this.logger.error({ err: error, reportId: report.id }, 'Could not enqueue report generation');
      await this.prisma.report.update({
        where: { id: report.id },
        data: { status: ReportStatus.FAILED, error: 'Could not start report generation.' },
      });
      throw Errors.serviceUnavailable(
        'Report generation is temporarily unavailable. Please try again.',
      );
    }
    return this.toDto(report);
  }

  async list(organizationId: string): Promise<ReportDto[]> {
    const reports = await this.prisma.report.findMany({
      where: { organizationId },
      orderBy: { createdAt: 'desc' },
      take: LIST_LIMIT,
    });
    return Promise.all(reports.map((report) => this.toDto(report)));
  }

  async get(organizationId: string, reportId: string): Promise<ReportDto> {
    const report = await this.prisma.report.findFirst({ where: { id: reportId, organizationId } });
    if (!report) throw Errors.notFound('Report');
    return this.toDto(report);
  }

  async toDto(report: Report): Promise<ReportDto> {
    const downloadUrl =
      report.status === ReportStatus.COMPLETED && report.storageKey
        ? await this.storage.presignDownload(report.storageKey, {
            fileName: report.fileName ?? 'report.csv',
          })
        : null;
    return {
      id: report.id,
      type: report.type,
      status: report.status,
      fileName: report.fileName,
      error: report.error,
      downloadUrl,
      createdAt: report.createdAt.toISOString(),
      completedAt: report.completedAt?.toISOString() ?? null,
    };
  }
}
